### ISSUE TITLE
The dialog popup does not scale to mobile

### ISSUE THREAD

**Issue by skeswa** [temple-acm/site#1]
Width is constrained to 800px. It needs to scale down in mobile mode (to some percent width of the screen methinks).

**Comment by ErezYehuda** [comment]
Should this just use a mobile CSS file?

**Comment by skeswa** [comment]
It should be powered by media queries, not a specific Mobile CSS file.

**Comment by ErezYehuda** [comment]
Which dialog popup are you referring to?

**Comment by skeswa** [comment]
The "card"-like popup that shows when you do registration or login. This refers to the revamp branch btw.

**Comment by skeswa** [comment]
Fixed in the latest few commits.
