### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by SriRamanujam** [temple-acm/site#11]
damned if we're going to let anybody do anything related to signing in or giving away PII through an unsecured connection. certs are cheap, we're buying one. or maybe, like, ten. Y'know, in case we lose the first one.

**Comment by skeswa** [comment]
+1

**Comment by SriRamanujam** [comment]
May or may not have gotten a cert. I'm still not sure if I did it right, though I suspect i did.

**Comment by skeswa** [comment]
Site now only works over SSL - otherwise it never sends a response. Make damn sure that HAProxy ensures only https traffic gets through.
