### ISSUE TITLE
Google calendar functions

### ISSUE THREAD

**Issue by SriRamanujam** [temple-acm/site#15]
split into two parts:

1) Receiving the calendar feed and parsing it into usable data
2) rendering that data to/for/on the client

**Comment by SriRamanujam** [comment]
backend done as of commit fc16eca2acffea9de0e15a448c3a2e9ac50e675d. Ignore its commit message, i jumped ahead of myself quite a bit.

**Comment by SriRamanujam** [comment]
Also, it's unsorted right now, which means there's no guarantee on the order in which your json items come back. I'll fix that later.

**Comment by skeswa** [comment]
Its sorted and cleaned up now.
