### ISSUE TITLE
Emailing functionality isn't set up

### ISSUE THREAD

**Issue by SriRamanujam** [temple-acm/site#18]
Just noticed that the email controller is totally empty. Do we want to have this up and running in time for tuesday?

**Comment by skeswa** [comment]
Meh. For now we could just pretend it works. It doesn't have to actually send emails at first.

**Comment by skeswa** [comment]
To elaborate: just make the dialog disappear when they hit submit.

**Comment by SriRamanujam** [comment]
I think for now it would be best if we removed the email us button and put it back up when we have time to flesh the functionality out. Doing that would be easier and cleaner.

**Comment by skeswa** [comment]
Ok, I agree for now. Lets leave this bug open though.

**Comment by SriRamanujam** [comment]
Okay, as seen in commit ea101a7e98bca78760d70b23ec5b3762c8235cea, the email us button is temporarily gone. We'll get around to it later.

**Comment by SriRamanujam** [comment]
It seems that we've got an Email Us button again, except it's just a mailto: link. Is that enough, or should we keep this open and build something more complicated?

**Comment by SriRamanujam** [comment]
Okay, bumping this issue. Now that we have email support, perhaps we can actually give people and "Email Us" card.

**Comment by SriRamanujam** [comment]
Right, closing this because mailto: links are good enough.
