### ISSUE TITLE
The "Contact Us" segment looks bad and we should feel bad

### ISSUE THREAD

**Issue by skeswa** [temple-acm/site#21]
We need to make that look better by all means. I mean, it does its job, but it needs to not be an eyesore. Also we need a button for the Temple ACM Slack chat client. ASAP.

**Comment by SriRamanujam** [comment]
Okay, added a slack button. 

What are your suggestions for making it look better? Do we want a stock photo of the new building or something?

**Comment by skeswa** [comment]
1. Replace grayish bg
2. Make buttons more colorful / attractive

Just mess with it a bit.

**Comment by skeswa** [comment]
El donerino.
