### ISSUE TITLE
Calendar text

### ISSUE THREAD

**Issue by stevenh44** [temple-acm/site#24]
Certain characters aren't being displayed correctly in the calendar section. "HTML isn't being escaped" -Sandile

**Comment by stevenh44** [comment]
Still an issue for the event title. 
![image](https://cloud.githubusercontent.com/assets/5866317/4128872/25da998e-3314-11e4-858c-199b50075de2.png)

**Comment by skeswa** [comment]
Uh why.

**Comment by skeswa** [comment]
Ugh. OK.

**Comment by stevenh44** [comment]
sorrrrry

**Comment by SriRamanujam** [comment]
it is fixed. again.
