### ISSUE TITLE
Fix Registration Controller

### ISSUE THREAD

**Issue by skeswa** [temple-acm/site#3]
It currently does not work. Fix that shit.

**Comment by skeswa** [comment]
So, I've set an ultimatum with myself that I will not sleep until this is done. Wish me luck / red bull.

**Comment by SriRamanujam** [comment]
Uh, godspeed?

**Comment by skeswa** [comment]
Godpeed.

**Comment by skeswa** [comment]
So, apparently I fucked up - looking into this.
