### ISSUE TITLE
Deploy revamped website

### ISSUE THREAD

**Issue by skeswa** [temple-acm/site#35]
Duh.

**Comment by SriRamanujam** [comment]
Shit what needs to be done for a successful deployment:

1) VM allocated (done)
2) Gulp confirmed working (done)
3) HAProxy configuration set to force all connections to go over HTTPS (done)
4) SSL cert deployed
5) Proper environment variables set

**Comment by skeswa** [comment]
1) Pending
2) Done
3) Pending
4) Pending
5) Pending

**Comment by SriRamanujam** [comment]
everything's done except the SSL cert. I'll make a new issue for it, targeted for friday.
