### ISSUE TITLE
Research Mongo DB not letting everybody connect to it

### ISSUE THREAD

**Issue by SriRamanujam** [temple-acm/site#50]
The mongo deployment on our db server currently lets everybody in the whole damn world connect to it. This is bad, that's where all our data is and it's not meant to be publically-readable. Let's lock it down to either user-based credentialed auth, or, if that's not possible, just the IP of the ACM webserver.

**Comment by SriRamanujam** [comment]
Okay, I am pretty sure that I have locked down access to just the superuser and the site's user. At least, when I try to connect without credentials I am denied access, so I'm going to consider that a win.

**Comment by skeswa** [comment]
How you do dis?

**Comment by SriRamanujam** [comment]
Effectively I just checked that all the roles were set up properly, and then restarted the mongo instance. I didn't actually change anything. Feel free to test and make sure I did it right.
