### ISSUE TITLE
URGENT: once deployed to production, new paypal ipn code must be tested

### ISSUE THREAD

**Issue by skeswa** [temple-acm/site#57]
So, recently I added authentication to the paypal callback so people couldn't just mark themselves paid. This means we have to test that it works on our acm.temple.edu domain. So we have to test this in production before releasing it to the world. NOTE: this requires vanilla HTTP _not HTTPS_ to work.

**Comment by SriRamanujam** [comment]
Summary: 

We did test it, about an hour before it went live. It didn't work, Sandile fixed it, done deal.
