### ISSUE TITLE
Slider timer is all weird

### ISSUE THREAD

**Issue by skeswa** [temple-acm/site#61]
If you mess with the slider it starts switching slides erratically.

**Comment by SriRamanujam** [comment]
It also seems to emphatically ignore SLIDER_DELAY, or at least SLIDER_DELAY isn't being read as milliseconds because it shifts way too fast

**Comment by SriRamanujam** [comment]
Did the jquery switchover fix this?

**Comment by skeswa** [comment]
yup.
